// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC90-AQR_V6T_bNvPaRrVFpAtjzYJAXTm0',
    appId: '1:789310177341:web:8781f595eb142083a3aa54',
    messagingSenderId: '789310177341',
    projectId: 'bus-app-iitu',
    authDomain: 'bus-app-iitu.firebaseapp.com',
    storageBucket: 'bus-app-iitu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWK4c9Ut1aA6WV2Ww3Tod_6x4QuyDhz8',
    appId: '1:789310177341:android:bca6c1ca07c1db71a3aa54',
    messagingSenderId: '789310177341',
    projectId: 'bus-app-iitu',
    storageBucket: 'bus-app-iitu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN84IeagZdLsXVU3c-e8QRJYf7Ldh2ev4',
    appId: '1:789310177341:ios:20754d64075a44b2a3aa54',
    messagingSenderId: '789310177341',
    projectId: 'bus-app-iitu',
    storageBucket: 'bus-app-iitu.appspot.com',
    iosBundleId: 'com.example.busApp',
  );
}
